### ISSUE TITLE
启用主题后，访问错误。

### ISSUE THREAD

**Issue by majinnn** [jiewenhuang/halo-theme-willing#1]
500 Internal Server Error
`Exception evaluating SpringEL expression: "menu.menuItems" (template: "modules/widgets/m-sidebar" - line 27, col 19)`
请看下

**Comment by jiewenhuang** [comment]
尝试去主题设置把该保存的都保存一下，特别是导航栏选择之类的。

**Comment by majinnn** [comment]
> 尝试去主题设置把该保存的都保存一下，特别是导航栏选择之类的。

感谢大佬，正常访问了。😁
